const CONFIG={
  date:"A little letter from my heart",
  greeting:"Hi Chibiii,",
  paragraphs:[
    `Hallooooow Sayang, BWAHAHAHAHAHAHHAHAHA.`,
    `Aku buatin nih buat kamu yang <span class="glowing-word">cantik lucu imut baik pinter dan chibii</span>, yang hari ini sedang berulangtahun ke 18.`,
    `Aku gabisa ngomong banyak karena yah ga jago ngomong, aku cuma mau bilang kalo aku itu makasi banget udah ditemenin sama kamu meski kamu nih sering <span class="glowing-word">ngeselin</span> ke aku.`,
    `Semoga kamu selalu diberikan berkah umur, dilancarkan rezekinya, dan segala keinginan kamu <span class="glowing-word">tercapai</span> ya sayangku.`,
    `Sekarang kamu udah ga kecil lagi sayang sekarang udah gede, jadi jangan banyak nangis lagi yaa sekarang harus kuat dan buat bangga keluarga kamu terutama buat <span class="glowing-word">almarhum ibu kamu.</span>`
  ],
  ending:"Happy Birthday Sayang LOVE UUUUUUUUUUUUUU. ♡",
  birthdayMessage:"Semoga kedepannya hidup kamu dipenuhi momen momen indah, kebahagiaan berlimpah, dan orang orang yang menyayangi kamu."
};
const $=id=>document.getElementById(id);const letterScene=$("letterScene"),envelope=$("envelope"),openButton=$("openButton"),letterView=$("letterView"),letterDate=$("letterDate"),letterGreeting=$("letterGreeting"),letterBody=$("letterBody"),letterEnding=$("letterEnding"),birthdayScene=$("birthdayScene"),birthdayMessage=$("birthdayMessage"),heartContainer=$("heartContainer"),replayButton=$("replayButton"),birthdayMusic=$("birthdayMusic"),musicButton=$("musicButton"),musicTitle=$("musicTitle");let hasOpened=false,cancelTyping=false,heartTimer=null;
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function init(){letterDate.textContent=CONFIG.date;birthdayMessage.textContent=CONFIG.birthdayMessage;openButton.addEventListener("click",openFromTap);envelope.addEventListener("click",openFromTap);envelope.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openFromTap()}});replayButton.addEventListener("click",replay);musicButton.addEventListener("click",toggleMusic);setupLightbox();startHearts()}
function openFromTap(){if(hasOpened)return;hasOpened=true;cancelTyping=false;startMusic();openLetter()}
function startMusic(){birthdayMusic.volume=.45;const p=birthdayMusic.play();if(p&&p.catch)p.catch(()=>{musicButton.textContent="▶";musicTitle.textContent="Tap ▶ untuk memutar musik ♡"})}
async function openLetter(){openButton.disabled=true;envelope.classList.add("opening");await wait(900);letterScene.style.display="none";letterView.classList.add("visible");letterView.setAttribute("aria-hidden","false");window.scrollTo(0,0);await wait(450);await typeText(letterGreeting,CONFIG.greeting,48,false);await wait(250);letterBody.innerHTML="";for(const text of CONFIG.paragraphs){if(cancelTyping)return;const p=document.createElement("p");letterBody.appendChild(p);await typeText(p,text,22,true);await wait(280)}await wait(350);await typeText(letterEnding,CONFIG.ending,42,false);await wait(900);burst();await wait(1200);letterView.classList.remove("visible");letterView.setAttribute("aria-hidden","true");await wait(400);birthdayScene.classList.add("visible");birthdayScene.setAttribute("aria-hidden","false");burst()}
async function typeText(el,html,base,rich){el.innerHTML="";const temp=document.createElement("div");temp.innerHTML=html;async function node(n,parent){if(cancelTyping)return;if(n.nodeType===Node.TEXT_NODE){for(const ch of n.textContent){if(cancelTyping)return;parent.appendChild(document.createTextNode(ch));await wait(ch==="."||ch==="!"||ch==="?"?base*5:ch===","?base*2.2:ch===" "?base*.35:base)}}else if(rich&&n.nodeType===Node.ELEMENT_NODE){const c=n.cloneNode(false);parent.appendChild(c);for(const child of n.childNodes)await node(child,c)}}for(const child of temp.childNodes)await node(child,el)}
function burst(){const cx=innerWidth/2,cy=innerHeight/2;for(let i=0;i<24;i++){const h=document.createElement("div");h.className="burst-heart";h.textContent=Math.random()>.4?"♥":"♡";h.style.left=cx+"px";h.style.top=cy+"px";const a=Math.random()*Math.PI*2,d=100+Math.random()*230;h.style.setProperty("--x",Math.cos(a)*d+"px");h.style.setProperty("--y",Math.sin(a)*d+"px");heartContainer.appendChild(h);setTimeout(()=>h.remove(),1600)}}
function startHearts(){clearInterval(heartTimer);heartTimer=setInterval(()=>{const h=document.createElement("div");h.className="floating-heart";h.textContent=Math.random()>.5?"♡":"♥";const d=7+Math.random()*7;h.style.left=Math.random()*100+"%";h.style.fontSize=10+Math.random()*13+"px";h.style.animationDuration=d+"s";h.style.setProperty("--drift",(Math.random()-.5)*160+"px");heartContainer.appendChild(h);setTimeout(()=>h.remove(),d*1000)},3000)}
function setupLightbox(){const box=$("photoLightbox"),img=$("lightboxImage"),cap=$("lightboxCaption");document.querySelectorAll(".polaroid").forEach(p=>p.addEventListener("click",()=>{img.src=p.dataset.image;cap.textContent=p.dataset.caption||"";box.classList.add("visible")}));const close=()=>box.classList.remove("visible");$("closeLightbox").addEventListener("click",close);box.addEventListener("click",e=>{if(e.target===box)close()});document.addEventListener("keydown",e=>{if(e.key==="Escape")close()})}
async function toggleMusic(){if(birthdayMusic.paused){try{await birthdayMusic.play()}catch{musicTitle.textContent="Tap ▶ untuk memutar musik ♡"}}else birthdayMusic.pause();updateMusicUI()}
function updateMusicUI(){if(birthdayMusic.paused){musicButton.textContent="▶";musicButton.classList.remove("playing");if(birthdayMusic.currentTime>0)musicTitle.textContent="Paused"}else{musicButton.textContent="❚❚";musicButton.classList.add("playing");musicTitle.textContent="Now playing ♡"}}
birthdayMusic.addEventListener("play",updateMusicUI);birthdayMusic.addEventListener("pause",updateMusicUI);
function replay(){cancelTyping=true;hasOpened=false;birthdayMusic.pause();birthdayMusic.currentTime=0;updateMusicUI();birthdayScene.classList.remove("visible");birthdayScene.setAttribute("aria-hidden","true");letterView.classList.remove("visible");letterView.setAttribute("aria-hidden","true");letterScene.style.display="flex";envelope.classList.remove("opening");openButton.disabled=false;letterGreeting.textContent="";letterBody.innerHTML="";letterEnding.textContent="";scrollTo(0,0);cancelTyping=false}
init();
